### PR TITLE
Release 0.3.1

### PR DESCRIPTION
**Pull request by jrbourbeau**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jrbourbeau** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
CI fails as there was no `sdist` added to PyPI

Screenshot 2023-11-29 at 12 18 58 PM

**Comment by jrbourbeau** [comment]
Ah, thanks for tracking that down @jakirkham

@fjetter @milesgranger would you mind pushing up a source distribution when you get a chance?

**Comment by milesgranger** [comment]
Didn't have direct rights to push to PyPI on the same tag, so just cut a new release (0.3.2) w/ the sdist. 
https://pypi.org/project/dask-glm/#files Hope that's alright.

**Comment by jrbourbeau** [comment]
Thanks @milesgranger -- closing in favor of https://github.com/conda-forge/dask-glm-feedstock/pull/8

**Pull request closed without merging**
